### ISSUE TITLE
Consistency needed in actor template schemas for g8client attribute

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#159]
See:
- In the [vdc](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/vdc/schema.hrd) actor template schema: `g8client = type:str consume:'g8client' auto`
- In the [uservdc](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/uservdc/schema.hrd) actor template schema: `g8client = type:str consume:'g8client`
- In the [autosnapshotting](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/autosnapshotting/schema.hrd) actor template: no `g8client` attribute

In the first it is `auto`, so why not auto in the second one?

And why no `g8client` attribute in the last one?  Bug?

**Comment by xmonader** [comment]
authosnapshotting actor uses the g8client of `vdc` 
https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/autosnapshotting/actions.py#L19

the core difference is when you specify `auto` in the schema it'll auto consume/auto create services needed, Otherwise you need to explicitly reference it.
https://github.com/Jumpscale/jumpscale_core8/blob/a111362fd83733adbdfea717c4ccd4397521e78f/lib/JumpScale/baselib/atyourservice81/Service.py#L145

**Comment by yveskerwyn** [comment]
Thanks @xmonader 
 
As discussed with @zaibon it is normal not to have a `g8client` attribute in the `autosnapshotting` actor template since it always depends on a parent `vdc` actor template

However, we should add `auto` to the `g8client` attribute in the `uservdc` actor template to make it consistent with the `vdc` actor template 

I created a new feature request for this: https://github.com/Jumpscale/ays_jumpscale8/issues/162
